import {
  readSharedTasks,
  syncSharedTaskStatus,
  subscribeSharedTasks,
  type SharedTaskRecord,
  type SharedTaskSnapshot,
} from "./shared-tasks";
import { resolveTodoIdentity } from "./todo-identity";
import {
  readFollowUpStatuses,
  persistFollowUpStatuses,
  subscribePersistenceErrors,
} from "./status-store";
import {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
  type FormEvent,
} from "react";
import type {
  DailyBriefConversationMessage,
  DailyBriefGenerationResult,
  DailyBriefReviewResult,
  Session,
  UiLanguage,
} from "./types";
import {
  ArrowLeft,
  Check,
  CircleAlert,
  ClipboardList,
  Clock3,
  MessageSquareText,
  RotateCw,
  Send,
  Sparkles,
  X,
} from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  buildDailyBrief,
  buildDailyBriefModelContext,
  type DailyBriefFollowUp,
  type DailyBriefFollowUpStatus,
} from "./daily-brief";

const dailyBriefCopy = {
  en: {
    assistantEyebrow: "DAILY ASSISTANT",
    back: "Back to home",
    chatDescription:
      "Review today’s transcripts with the language model configured in Settings.",
    chatEmpty: "Your questions and the assistant’s answers will appear here.",
    chatFailed: (message: string) => `Review failed. ${message}`,
    chatPlaceholder: "Ask about today…",
    chatQuestionAria: "Ask the daily assistant",
    chatTitle: "Continue the review",
    chatting: "Reviewing…",
    characterUnit: "characters",
    complete: "Complete",
    completed: "Completed",
    dismiss: "Ignore",
    dismissed: "Ignored",
    durationUnit: "minutes",
    emptyDescription:
      "Once you speak today, ViTalk will organize your latest content here.",
    emptyTitle: "No brief to review yet",
    entryAction: "View today’s brief",
    entryDescription: (sessions: number, followUps: number) =>
      sessions > 0
        ? `${sessions} sessions organized · ${followUps} items to confirm`
        : "Your daily review will be ready after your first session.",
    entryStatus: "Local draft",
    entryTitle: "Today’s brief",
    followUpDescription:
      "These are possible commitments, not confirmed unfinished tasks.",
    followUpTitle: "To confirm",
    generatedBy: (model: string) => `Generated by ${model}`,
    generating: "Generating with your configured model…",
    generationFailed: (message: string) =>
      `Model generation failed. The local draft remains visible. ${message}`,
    headline: (sessions: number, highlights: number, followUps: number) =>
      `Today ViTalk organized ${sessions} sessions into ${highlights} highlights and found ${followUps} items worth confirming.`,
    highlightDescription: "Recent successful transcripts from today.",
    highlightTitle: "Highlights",
    localDraft: "Local first-pass",
    noFollowUps: "No items need confirmation right now.",
    pageTitle: "Today’s brief",
    pending: "Pending",
    send: "Send question",
    regenerate: "Regenerate summary",
    sessionUnit: "sessions",
    sourceFallback: "ViTalk",
    todayLabel: "TODAY",
  },
  "zh-CN": {
    assistantEyebrow: "理性每日助理",
    back: "返回首页",
    chatDescription: "使用设置页已配置的大语言模型，围绕今天的转写继续复盘。",
    chatEmpty: "你的问题和每日助理的回答会出现在这里。",
    chatFailed: (message: string) => `复盘失败。${message}`,
    chatPlaceholder: "问问今天说过的内容…",
    chatQuestionAria: "向每日助理提问",
    chatTitle: "继续复盘",
    chatting: "正在复盘…",
    characterUnit: "字",
    complete: "完成",
    completed: "已完成",
    dismiss: "忽略",
    dismissed: "已忽略",
    durationUnit: "分钟",
    emptyDescription: "今天开始表达后，ViTalk 会在这里整理最新内容。",
    emptyTitle: "今天还没有可整理的内容",
    entryAction: "查看今日简报",
    entryDescription: (sessions: number, followUps: number) =>
      sessions > 0
        ? `已整理 ${sessions} 次表达 · ${followUps} 项待确认`
        : "完成今天的第一次表达后，这里会生成回顾。",
    entryStatus: "本地初步整理",
    entryTitle: "今日简报",
    followUpDescription: "以下是潜在承诺，不代表系统认定你尚未完成。",
    followUpTitle: "待确认事项",
    generatedBy: (model: string) => `由 ${model} 生成`,
    generating: "正在使用设置页模型生成…",
    generationFailed: (message: string) =>
      `模型总结生成失败，当前仍显示本地初步整理。${message}`,
    headline: (sessions: number, highlights: number, followUps: number) =>
      `今天共整理 ${sessions} 次表达，形成 ${highlights} 条重点，并发现 ${followUps} 项值得确认的事项。`,
    highlightDescription: "来自今天成功转写的重点内容。",
    highlightTitle: "今日重点",
    localDraft: "本地初步整理",
    noFollowUps: "目前没有需要确认的事项。",
    pageTitle: "今日简报",
    pending: "待确认",
    send: "发送问题",
    regenerate: "重新生成总结",
    sessionUnit: "次表达",
    sourceFallback: "ViTalk",
    todayLabel: "今天",
  },
} as const;

export function getDailyBriefCopy(language: UiLanguage) {
  return dailyBriefCopy[language];
}

export function DailyBriefPage({
  language,
  onGenerate,
  onReview,
  onBack,
  sessions,
}: {
  language: UiLanguage;
  onGenerate: (
    content: string,
    language: UiLanguage,
  ) => Promise<DailyBriefGenerationResult>;
  onReview: (
    reviewContext: string,
    question: string,
    conversation: DailyBriefConversationMessage[],
    language: UiLanguage,
  ) => Promise<DailyBriefReviewResult>;
  onBack: () => void;
  sessions: Session[];
}) {
  const copy = getDailyBriefCopy(language);
  const brief = useMemo(() => buildDailyBrief(sessions), [sessions]);
  const modelContext = useMemo(
    () => buildDailyBriefModelContext(sessions),
    [sessions],
  );
  const [modelSummary, setModelSummary] =
    useState<DailyBriefGenerationResult | null>(null);
  const [generationState, setGenerationState] = useState<
    "idle" | "generating" | "ready" | "error"
  >("idle");
  const [generationError, setGenerationError] = useState<string | null>(null);
  const generatedContextRef = useRef<string | null>(null);
  const [followUpStatuses, setFollowUpStatuses] = useState<
    Record<string, DailyBriefFollowUpStatus>
  >(() => readFollowUpStatuses(brief.dateKey));
  const [todoRecords, setTodoRecords] = useState<SharedTaskRecord[]>([]);
  const [todoSyncError, setTodoSyncError] = useState("");
  const [todoSyncBusy, setTodoSyncBusy] = useState(false);
  useEffect(() => subscribePersistenceErrors(setTodoSyncError), []);
  const applyTodoSnapshot = useCallback(
    (snapshot: SharedTaskSnapshot) => {
      setTodoRecords(
        snapshot.records.filter((record) => record.kind === "todo"),
      );
      const updates: Record<string, DailyBriefFollowUpStatus> = {};
      for (const record of snapshot.records) {
        if (record.kind !== "todo" || !record.id.startsWith("todo:")) continue;
        updates[record.id.slice(5)] =
          record.status === "completed"
            ? "completed"
            : record.status === "dismissed"
              ? "dismissed"
              : "pending";
      }
      setFollowUpStatuses((current) => {
        const next = { ...current, ...updates };
        persistFollowUpStatuses(brief.dateKey, next);
        return next;
      });
    },
    [brief.dateKey],
  );
  useEffect(() => {
    let disposed = false;
    const refresh = async () => {
      try {
        const snapshot = await readSharedTasks();
        if (!disposed) applyTodoSnapshot(snapshot);
      } catch (error) {
        if (!disposed) setTodoSyncError(`事项状态读取失败：${String(error)}`);
      }
    };
    void refresh();
    const remove = subscribeSharedTasks(() => void refresh(), setTodoSyncError);
    return () => {
      disposed = true;
      remove();
    };
  }, [applyTodoSnapshot]);
  const [question, setQuestion] = useState("");
  const [messages, setMessages] = useState<
    Array<{ id: number; role: "assistant" | "user"; text: string }>
  >([]);
  const [questionState, setQuestionState] = useState<
    "idle" | "asking" | "error"
  >("idle");
  const [questionError, setQuestionError] = useState<string | null>(null);
  const dateLabel = new Intl.DateTimeFormat(language, {
    month: "long",
    day: "numeric",
    weekday: "long",
  }).format(new Date());
  const followUps = useMemo(
    () =>
      brief.followUps.map((item) => {
        const id = resolveTodoIdentity(item, todoRecords);
        return { ...item, id, status: followUpStatuses[id] ?? item.status };
      }),
    [brief.followUps, followUpStatuses, todoRecords],
  );
  const reviewContext = useMemo(
    () =>
      JSON.stringify({
        dailyTranscripts: modelContext,
        generatedSummary: modelSummary?.summary ?? null,
        followUps: followUps.map(({ status, text }) => ({ status, text })),
      }),
    [followUps, modelContext, modelSummary?.summary],
  );

  const handleRegenerate = useCallback(async () => {
    if (!modelContext) return;
    setGenerationState("generating");
    setGenerationError(null);
    try {
      const result = await onGenerate(modelContext, language);
      setModelSummary(result);
      setGenerationState("ready");
    } catch (error) {
      setGenerationState("error");
      setGenerationError(
        error instanceof Error ? error.message : String(error ?? ""),
      );
    }
  }, [language, modelContext, onGenerate]);

  useEffect(() => {
    if (!modelContext || generatedContextRef.current === modelContext) return;
    generatedContextRef.current = modelContext;
    void handleRegenerate();
  }, [handleRegenerate, modelContext]);

  const updateFollowUp = async (
    id: string,
    status: DailyBriefFollowUpStatus,
  ) => {
    if (todoSyncBusy) return;
    setTodoSyncBusy(true);
    setTodoSyncError("");
    try {
      const snapshot = await syncSharedTaskStatus(
        id,
        status === "pending" ? "active" : status,
      );
      applyTodoSnapshot(snapshot);
    } catch (error) {
      setTodoSyncError(
        `事项状态未保存：${error instanceof Error ? error.message : String(error)}`,
      );
    } finally {
      setTodoSyncBusy(false);
    }
  };

  const handleQuestion = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const trimmedQuestion = question.trim();
    if (!trimmedQuestion || questionState === "asking") return;

    const id = Date.now();
    const conversation = messages.map(({ role, text }) => ({ role, text }));
    setMessages((items) => [
      ...items,
      { id, role: "user", text: trimmedQuestion },
    ]);
    setQuestion("");
    setQuestionState("asking");
    setQuestionError(null);
    try {
      const result = await onReview(
        reviewContext,
        trimmedQuestion,
        conversation,
        language,
      );
      setMessages((items) => [
        ...items,
        { id: id + 1, role: "assistant", text: result.answer },
      ]);
      setQuestionState("idle");
    } catch (error) {
      setQuestionState("error");
      setQuestionError(
        error instanceof Error ? error.message : String(error ?? ""),
      );
    }
  };

  return (
    <main className="daily-brief-page" aria-label={copy.pageTitle}>
      <div className="daily-brief-scroll">
        <div className="daily-brief-frame">
          {todoSyncError && <p role="alert">{todoSyncError}</p>}
          {todoSyncBusy && <p role="status">正在保存事项状态…</p>}
          <header className="daily-brief-header">
            <Button onClick={onBack} type="button" variant="ghost">
              <ArrowLeft size={16} strokeWidth={1.9} aria-hidden="true" />
              {copy.back}
            </Button>
            <div>
              <span>{copy.todayLabel}</span>
              <strong>{dateLabel}</strong>
            </div>
          </header>

          <section
            className="daily-brief-cover"
            aria-labelledby="daily-brief-title"
          >
            <div className="daily-brief-cover-copy">
              <div className="daily-brief-cover-toolbar">
                <div className="daily-brief-cover-kicker" aria-live="polite">
                  <Sparkles size={15} strokeWidth={1.8} aria-hidden="true" />
                  <span>
                    {generationState === "generating"
                      ? copy.generating
                      : modelSummary
                        ? copy.generatedBy(modelSummary.modelName)
                        : copy.localDraft}
                  </span>
                </div>
                <Button
                  aria-label={copy.regenerate}
                  className="daily-brief-regenerate"
                  disabled={!modelContext || generationState === "generating"}
                  onClick={() => void handleRegenerate()}
                  size="sm"
                  type="button"
                  variant="outline"
                >
                  <RotateCw
                    className={
                      generationState === "generating"
                        ? "is-spinning"
                        : undefined
                    }
                    size={14}
                    strokeWidth={1.9}
                    aria-hidden="true"
                  />
                  <span>{copy.regenerate}</span>
                </Button>
              </div>
              <h1 id="daily-brief-title">{copy.pageTitle}</h1>
              <p>
                {modelSummary?.summary ??
                  (brief.stats.sessionCount > 0
                    ? copy.headline(
                        brief.stats.sessionCount,
                        brief.highlights.length,
                        brief.followUps.length,
                      )
                    : copy.emptyDescription)}
              </p>
              {generationState === "error" && generationError ? (
                <p className="daily-brief-generation-error" role="status">
                  {copy.generationFailed(generationError)}
                </p>
              ) : null}
              {brief.sourceApps.length > 0 ? (
                <div className="daily-brief-sources">
                  {brief.sourceApps.map((source) => (
                    <span key={source}>{source}</span>
                  ))}
                </div>
              ) : null}
            </div>
            <dl className="daily-brief-stats">
              <div>
                <dt>{copy.sessionUnit}</dt>
                <dd>{brief.stats.sessionCount}</dd>
              </div>
              <div>
                <dt>{copy.characterUnit}</dt>
                <dd>{brief.stats.characterCount}</dd>
              </div>
              <div>
                <dt>{copy.durationUnit}</dt>
                <dd>{brief.stats.durationMinutes}</dd>
              </div>
            </dl>
          </section>

          {brief.stats.sessionCount === 0 ? (
            <section className="daily-brief-empty">
              <ClipboardList size={22} strokeWidth={1.7} aria-hidden="true" />
              <div>
                <h2>{copy.emptyTitle}</h2>
                <p>{copy.emptyDescription}</p>
              </div>
            </section>
          ) : (
            <div className="daily-brief-columns">
              <BriefSection
                description={copy.highlightDescription}
                icon={<Clock3 size={17} strokeWidth={1.8} aria-hidden="true" />}
                title={copy.highlightTitle}
              >
                <ol className="daily-brief-highlights">
                  {brief.highlights.map((item) => (
                    <li key={item.id}>
                      <time dateTime={new Date(item.createdAt).toISOString()}>
                        {formatTime(item.createdAt, language)}
                      </time>
                      <p>{item.text}</p>
                      <span>{item.source || copy.sourceFallback}</span>
                    </li>
                  ))}
                </ol>
              </BriefSection>

              <BriefSection
                description={copy.followUpDescription}
                icon={
                  <CircleAlert size={17} strokeWidth={1.8} aria-hidden="true" />
                }
                title={copy.followUpTitle}
              >
                {followUps.length > 0 ? (
                  <ul className="daily-brief-followups">
                    {followUps.map((item) => (
                      <FollowUpItem
                        copy={copy}
                        item={item}
                        key={item.id}
                        onUpdate={updateFollowUp}
                      />
                    ))}
                  </ul>
                ) : (
                  <p className="daily-brief-section-empty">
                    {copy.noFollowUps}
                  </p>
                )}
              </BriefSection>
            </div>
          )}

          <BriefSection
            className="daily-brief-chat"
            description={copy.chatDescription}
            icon={
              <MessageSquareText
                size={17}
                strokeWidth={1.8}
                aria-hidden="true"
              />
            }
            title={copy.chatTitle}
          >
            <div className="daily-brief-chat-log" aria-live="polite">
              {messages.length > 0 ? (
                messages.map((message) => (
                  <p className={`is-${message.role}`} key={message.id}>
                    {message.text}
                  </p>
                ))
              ) : (
                <span>{copy.chatEmpty}</span>
              )}
              {questionState === "asking" ? <span>{copy.chatting}</span> : null}
              {questionState === "error" && questionError ? (
                <span className="daily-brief-chat-error" role="status">
                  {copy.chatFailed(questionError)}
                </span>
              ) : null}
            </div>
            <form
              className="daily-brief-chat-form"
              onSubmit={(event) => void handleQuestion(event)}
            >
              <Input
                aria-label={copy.chatQuestionAria}
                onChange={(event) => setQuestion(event.target.value)}
                placeholder={copy.chatPlaceholder}
                value={question}
              />
              <Button
                aria-label={copy.send}
                disabled={!question.trim() || questionState === "asking"}
                type="submit"
              >
                <Send size={16} strokeWidth={1.9} aria-hidden="true" />
                <span>{copy.send}</span>
              </Button>
            </form>
          </BriefSection>
        </div>
      </div>
    </main>
  );
}

function BriefSection({
  children,
  className,
  description,
  icon,
  title,
}: {
  children: React.ReactNode;
  className?: string;
  description: string;
  icon: React.ReactNode;
  title: string;
}) {
  return (
    <section
      className={
        className ? `daily-brief-section ${className}` : "daily-brief-section"
      }
    >
      <header>
        <span aria-hidden="true">{icon}</span>
        <div>
          <h2>{title}</h2>
          <p>{description}</p>
        </div>
      </header>
      {children}
    </section>
  );
}

function FollowUpItem({
  copy,
  item,
  onUpdate,
}: {
  copy: ReturnType<typeof getDailyBriefCopy>;
  item: DailyBriefFollowUp;
  onUpdate: (id: string, status: DailyBriefFollowUpStatus) => void;
}) {
  if (item.id.startsWith("unbound:")) {
    return (
      <li>
        <p>{item.text}</p>
        <small>
          {copy.complete === "完成"
            ? "正在核对事项来源；若持续未匹配，请到近期事项查看，暂不能更改状态。"
            : "Checking the source. If it remains unmatched, review Recent items before changing its status."}
        </small>
      </li>
    );
  }
  if (item.status !== "pending") {
    return (
      <li className={`is-${item.status}`}>
        <span className="daily-brief-followup-status">
          {item.status === "completed" ? (
            <Check size={15} strokeWidth={2} aria-hidden="true" />
          ) : (
            <X size={15} strokeWidth={2} aria-hidden="true" />
          )}
          {item.status === "completed" ? copy.completed : copy.dismissed}
        </span>
        <p>{item.text}</p>
        <Button
          type="button"
          size="sm"
          variant="ghost"
          onClick={() => onUpdate(item.id, "pending")}
        >
          {copy.complete === "完成" ? "恢复待办" : "Reopen"}
        </Button>
      </li>
    );
  }

  return (
    <li>
      <Badge variant="outline">{copy.pending}</Badge>
      <p>{item.text}</p>
      <div>
        <Button
          aria-label={`${copy.complete === "完成" ? "将" : ""}“${item.text}”${copy.complete === "完成" ? "标记为已完成" : " mark complete"}`}
          onClick={() => onUpdate(item.id, "completed")}
          size="sm"
          type="button"
          variant="outline"
        >
          <Check size={14} strokeWidth={2} aria-hidden="true" />
          {copy.complete}
        </Button>
        <Button
          aria-label={`${copy.dismiss} “${item.text}”`}
          onClick={() => onUpdate(item.id, "dismissed")}
          size="sm"
          type="button"
          variant="ghost"
        >
          {copy.dismiss}
        </Button>
      </div>
    </li>
  );
}

function formatTime(timestamp: number, language: UiLanguage): string {
  return new Intl.DateTimeFormat(language, {
    hour: "2-digit",
    minute: "2-digit",
  }).format(new Date(timestamp));
}
